name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install dependencies for each service
      - run: npm --prefix services/packages/common ci
      - run: npm --prefix gatewayservice ci
      - run: npm --prefix webapp ci
      - run: npm --prefix services/authservice ci
      - run: npm --prefix services/academicservice ci
      - run: npm --prefix services/evalservice ci
      - run: npm --prefix services/gradeservice ci
      - run: npm --prefix services/auditservice ci

      # Run tests with coverage for each service
      - run: npm --prefix services/packages/common test -- --coverage
      - run: npm --prefix gatewayservice test -- --coverage
      - run: npm --prefix webapp test -- --coverage
      - run: npm --prefix services/authservice test -- --coverage
      - run: npm --prefix services/academicservice test -- --coverage
      - run: npm --prefix services/evalservice test -- --coverage
      - run: npm --prefix services/gradeservice test -- --coverage
      - run: npm --prefix services/auditservice test -- --coverage

      # SonarQube analysis 
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
