name: Release Pipeline

on:
  release:
    types: [published]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install dependencies for each service
      - run: npm --prefix gatewayservice ci
      - run: npm --prefix webapp ci

      # Run tests with coverage for each service
      - run: npm --prefix gatewayservice test -- --coverage
      - run: npm --prefix webapp test -- --coverage

      # SonarQube analysis
      # - name: Analyze with SonarQube
      #   uses: SonarSource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm --prefix gatewayservice ci
      - run: npm --prefix webapp ci

      - run: npm --prefix webapp run build
        env:
          DISABLE_ESLINT_PLUGIN: true
      - run: npm --prefix webapp run test:e2e

  docker-push-gatewayservice:
    name: Push GatewayService Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [e2e-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Publish GatewayService Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          #name: your-dockerhub-username/gatewayservice
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: gatewayservice/Dockerfile

  docker-push-webapp:
    name: Push WebApp Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [e2e-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Publish WebApp Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          #name: your-dockerhub-username/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: webapp/Dockerfile

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs:
      - docker-push-gatewayservice
      - docker-push-webapp
    steps:
      - name: Deploy over SSH
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          #command: |
           # wget https://raw.githubusercontent.com/your-github-username/UniEval-TFG/master/docker-compose.yml -O docker-compose.yml
           # docker compose --profile prod down
           # docker compose --profile prod up -d --pull always